# Copyright 2024-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8

CRATES="
"

RUST_MIN_VER="1.95"
inherit cargo

DESCRIPTION="A REPL for Rust"
HOMEPAGE="https://github.com/evcxr/evcxr"
SRC_URI="
	https://github.com/evcxr/evcxr/archive/v${PV}.tar.gz -> evcxr-${PV}.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://github.com/wangjiezhe/gentoo-go-deps/releases/download/${P}/evcxr_repl-${PV}-crates.tar.xz
	"
fi

S="${WORKDIR}/evcxr-${PV}/evcxr_repl"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions Boost-1.0 CC0-1.0 ISC MIT
	MPL-2.0 Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"
