# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8

CRATES="
"

RUST_MIN_VER="1.88.0"
inherit cargo

DESCRIPTION="[CLI] Extremely fast and smart HTML + JS + CSS minifier"
HOMEPAGE="https://github.com/wilsonzlin/minify-html"
SRC_URI="
	https://github.com/wilsonzlin/minify-html/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://github.com/wangjiezhe/gentoo-go-deps/releases/download/${P}/${P}-crates.tar.xz
	"
fi

S="${WORKDIR}/${P}/minhtml"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD ISC MIT MPL-2.0
	Unicode-3.0
"
SLOT="0"
KEYWORDS="~amd64"

# PARENT_PATCHES=(
# 	"${FILESDIR}/${PN}-0.16.4-cargo.patch"
# )

DOCS=( README.md )

# src_prepare() {
# 	cd "${WORKDIR}/${P}" || die
# 	[[ -n "${PARENT_PATCHES[@]}" ]] && eapply "${PARENT_PATCHES[@]}"
# 	eapply_user
# }

src_install() {
	cargo_src_install

	einstalldocs
}
