# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.3

EAPI=8

CRATES="
	adler2@2.0.1
	ahash@0.7.8
	ahash@0.8.12
	aho-corasick@1.1.3
	allocator-api2@0.2.21
	ansi_term@0.12.1
	atty@0.2.14
	autocfg@1.5.0
	base64-simd@0.7.0
	base64-simd@0.8.0
	bincode@2.0.1
	bincode_derive@2.0.1
	bitflags@1.3.2
	bitflags@2.10.0
	bitvec@1.0.1
	bumpalo@3.19.0
	bytecheck@0.6.12
	bytecheck_derive@0.6.12
	bytes@1.10.1
	castaway@0.2.4
	cfg-if@1.0.4
	clap@2.34.0
	compact_str@0.9.0
	const-str-proc-macro@0.3.2
	const-str@0.3.2
	convert_case@0.6.0
	cow-utils@0.1.3
	crc32fast@1.5.0
	crossbeam-deque@0.8.6
	crossbeam-epoch@0.9.18
	crossbeam-utils@0.8.21
	cssparser-color@0.1.0
	cssparser-macros@0.6.1
	cssparser@0.33.0
	dashmap@5.5.3
	data-encoding@2.9.0
	data-url@0.1.1
	deranged@0.5.4
	dragonbox_ecma@0.0.5
	dtoa-short@0.3.5
	dtoa@1.0.10
	either@1.15.0
	equivalent@1.0.2
	fastrand@2.3.0
	flate2@1.1.5
	funty@2.0.0
	getrandom@0.2.16
	getrandom@0.3.4
	hashbrown@0.12.3
	hashbrown@0.14.5
	hashbrown@0.16.0
	heck@0.3.3
	hermit-abi@0.1.19
	indexmap@2.12.0
	itertools@0.10.5
	itertools@0.14.0
	itoa@1.0.15
	js-sys@0.3.81
	json-escape-simd@3.0.1
	lazy_static@1.5.0
	libc@0.2.177
	lightningcss-derive@1.0.0-alpha.43
	lightningcss@1.0.0-alpha.68
	lock_api@0.4.14
	log@0.4.28
	matches@0.1.10
	memchr@2.7.6
	miniz_oxide@0.8.9
	nom@8.0.0
	nonmax@0.5.5
	num-bigint@0.4.6
	num-conv@0.1.0
	num-integer@0.1.46
	num-traits@0.2.19
	once_cell@1.21.3
	outref@0.1.0
	outref@0.5.2
	owo-colors@4.2.3
	oxc-browserslist@2.1.2
	oxc-miette-derive@2.5.1
	oxc-miette@2.5.1
	oxc_allocator@0.95.0
	oxc_ast@0.95.0
	oxc_ast_macros@0.95.0
	oxc_ast_visit@0.95.0
	oxc_codegen@0.95.0
	oxc_compat@0.95.0
	oxc_data_structures@0.95.0
	oxc_diagnostics@0.95.0
	oxc_ecmascript@0.95.0
	oxc_estree@0.95.0
	oxc_index@4.1.0
	oxc_mangler@0.95.0
	oxc_minifier@0.95.0
	oxc_parser@0.95.0
	oxc_regular_expression@0.95.0
	oxc_semantic@0.95.0
	oxc_sourcemap@6.0.0
	oxc_span@0.95.0
	oxc_syntax@0.95.0
	oxc_traverse@0.95.0
	parcel_selectors@0.28.2
	parcel_sourcemap@2.1.1
	parking_lot_core@0.9.12
	pastey@0.1.1
	pathdiff@0.2.3
	percent-encoding@2.3.2
	phf@0.11.3
	phf@0.13.1
	phf_codegen@0.11.3
	phf_generator@0.11.3
	phf_generator@0.13.1
	phf_macros@0.11.3
	phf_macros@0.13.1
	phf_shared@0.11.3
	phf_shared@0.13.1
	powerfmt@0.2.0
	precomputed-hash@0.1.1
	proc-macro-error-attr@1.0.4
	proc-macro-error@1.0.4
	proc-macro2@1.0.103
	ptr_meta@0.1.4
	ptr_meta_derive@0.1.4
	quote@1.0.41
	r-efi@5.3.0
	radium@0.7.0
	rand@0.8.5
	rand_core@0.6.4
	rayon-core@1.13.0
	rayon@1.11.0
	redox_syscall@0.5.18
	rend@0.4.2
	rkyv@0.7.45
	rkyv_derive@0.7.45
	rustc-hash@2.1.1
	rustversion@1.0.22
	ryu@1.0.20
	scopeguard@1.2.0
	seahash@4.1.0
	self_cell@1.2.1
	seq-macro@0.3.6
	serde-content@0.1.2
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.145
	simd-abstraction@0.7.1
	simd-adler32@0.3.7
	simdutf8@0.1.5
	siphasher@1.0.1
	smallvec@1.15.1
	smawk@0.3.2
	static_assertions@1.1.0
	strsim@0.8.0
	structopt-derive@0.4.18
	structopt@0.3.26
	syn@1.0.109
	syn@2.0.108
	tap@1.0.1
	textwrap@0.11.0
	textwrap@0.16.2
	thiserror-impl@2.0.17
	thiserror@2.0.17
	time-core@0.1.6
	time@0.3.44
	tinyvec@1.10.0
	tinyvec_macros@0.1.1
	unicode-id-start@1.4.0
	unicode-ident@1.0.20
	unicode-linebreak@0.1.5
	unicode-segmentation@1.12.0
	unicode-width@0.1.14
	unicode-width@0.2.2
	unty@0.0.4
	uuid@1.18.1
	vec_map@0.8.2
	version_check@0.9.5
	virtue@0.0.18
	vlq@0.5.1
	vsimd@0.8.0
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.1+wasi-0.2.4
	wasm-bindgen-backend@0.2.104
	wasm-bindgen-macro-support@0.2.104
	wasm-bindgen-macro@0.2.104
	wasm-bindgen-shared@0.2.104
	wasm-bindgen@0.2.104
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-link@0.2.1
	wit-bindgen@0.46.0
	wyz@0.5.1
	zerocopy-derive@0.8.27
	zerocopy@0.8.27
"

RUST_MIN_VER="1.88.0"
inherit cargo

DESCRIPTION="[CLI] Extremely fast and smart HTML + JS + CSS minifier"
HOMEPAGE="https://github.com/wilsonzlin/minify-html"
SRC_URI="
	https://github.com/wilsonzlin/minify-html/archive/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

S="${WORKDIR}/${P}/minhtml"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 MIT MPL-2.0 Unicode-3.0
	|| ( Apache-2.0-with-LLVM-exceptions Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"

PARENT_PATCHES=(
	"${FILESDIR}/${PN}-0.16.4-cargo.patch"
)

DOCS=( README.md )

src_prepare() {
	cd "${WORKDIR}/${P}" || die
	[[ -n "${PARENT_PATCHES[@]}" ]] && eapply "${PARENT_PATCHES[@]}"
	eapply_user
}

src_install() {
	cargo_src_install

	einstalldocs
}
