# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.1

EAPI=8

CRATES="
"

RUST_MIN_VER="1.88.0"
inherit cargo shell-completion toolchain-funcs

DESCRIPTION="A friendly terminal Markdown previewer"
HOMEPAGE="https://github.com/RivoLink/leaf"
SRC_URI="
	https://github.com/RivoLink/leaf/archive/${PV}.tar.gz -> ${P}.gh.tar.gz
	${CARGO_CRATE_URIS}
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://github.com/wangjiezhe/gentoo-go-deps/releases/download/${P}/${P}-crates.tar.xz
	"
fi

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD CDLA-Permissive-2.0 ISC LPPL-1.3c MIT Unicode-3.0
	Unicode-DFS-2016 WTFPL-2 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="test"
RESTRICT="!test? ( test )"

DOCS=( README.md CHANGELOG.md )

src_install() {
	cargo_src_install

	einstalldocs

	if ! tc-is-cross-compiler; then
		local leaf="${ED}"/usr/bin/leaf
		for shell in bash fish zsh; do
			"${leaf}" --auto-complete "${shell}:dump" > "${T}/${PN}.${shell}" || die
		done
		newbashcomp "${T}"/${PN}.bash ${PN}
		dofishcomp "${T}"/${PN}.fish
		newzshcomp "${T}"/${PN}.zsh _${PN}
	else
		ewarn "shell completions files were skipped due to cross-compliation"
	fi
}
