# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.17.0

EAPI=8

DIST_AUTHOR="JACQUESG"
DIST_VERSION="0.05"


inherit perl-module

DESCRIPTION="Perl bindings to the msgpack C library"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="amd64"
IUSE=""

DEPEND=">=dev-perl/Test-Pod-1.520.0
	>=dev-perl/Test-Pod-Coverage-1.100.0
	dev-lang/perl"
