# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.1

EAPI=8

PYTHON_COMPAT=( python3_{10..12} )
DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=maturin

CRATES="
	aho-corasick@1.0.2
	autocfg@1.1.0
	bitflags@1.3.2
	byteorder@1.4.3
	cedarwood@0.4.6
	cfg-if@1.0.0
	fxhash@0.2.1
	hashbrown@0.14.0
	indoc@1.0.9
	jieba-rs@0.6.8
	lazy_static@1.4.0
	libc@0.2.147
	lock_api@0.4.10
	memchr@2.5.0
	memoffset@0.9.0
	once_cell@1.18.0
	parking_lot@0.12.1
	parking_lot_core@0.9.8
	phf@0.11.2
	phf_codegen@0.11.2
	phf_generator@0.11.2
	phf_shared@0.11.2
	proc-macro2@1.0.65
	pyo3-build-config@0.19.1
	pyo3-ffi@0.19.1
	pyo3-macros-backend@0.19.1
	pyo3-macros@0.19.1
	pyo3@0.19.1
	quote@1.0.30
	rand@0.8.5
	rand_core@0.6.4
	redox_syscall@0.3.5
	regex-automata@0.3.3
	regex-syntax@0.7.4
	regex@1.9.1
	scopeguard@1.1.0
	siphasher@0.3.10
	smallvec@1.11.0
	syn@1.0.109
	target-lexicon@0.12.9
	unicode-ident@1.0.11
	unindent@0.1.11
	windows-targets@0.48.1
	windows_aarch64_gnullvm@0.48.0
	windows_aarch64_msvc@0.48.0
	windows_i686_gnu@0.48.0
	windows_i686_msvc@0.48.0
	windows_x86_64_gnu@0.48.0
	windows_x86_64_gnullvm@0.48.0
	windows_x86_64_msvc@0.48.0
"

inherit distutils-r1 cargo

DESCRIPTION="jieba-rs Python binding"
HOMEPAGE="https://github.com/messense/rjieba-py"
SRC_URI="
	${CARGO_CRATE_URIS}
	https://github.com/messense/rjieba-py/archive/v${PV}.tar.gz -> ${P}.gh.tar.gz
"
S="${WORKDIR}/${PN}-py-${PV}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 MIT
	Unicode-DFS-2016
"
SLOT="0"
KEYWORDS="~amd64"

src_configure() {
	export RUSTFLAGS="${RUSTFLAGS}"
	cargo_src_configure
}

src_compile() {
	cargo_src_compile

	python_copy_sources
	distutils-r1_src_compile
}

src_install() {
	distutils-r1_src_install
}

distutils_enable_tests pytest

src_test() {
	cargo_src_test

	rm -rf rjieba || die
	distutils-r1_src_test
}
