# Copyright 2024-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.1

EAPI=8

PYTHON_COMPAT=( python3_{11..14} python3_{13,14}t )
DISTUTILS_EXT=1
DISTUTILS_USE_PEP517=maturin

CRATES="
"

RUST_MIN_VER="1.87.0"
inherit distutils-r1 cargo

DESCRIPTION="jieba-rs Python binding"
HOMEPAGE="https://github.com/messense/rjieba-py"
SRC_URI="
	${CARGO_CRATE_URIS}
	https://github.com/messense/rjieba-py/archive/v${PV}.tar.gz -> ${P}.gh.tar.gz
"
if [[ ${PKGBUMPING} != ${PVR} ]]; then
	SRC_URI+="
		https://github.com/wangjiezhe/gentoo-go-deps/releases/download/${P}/${P}-crates.tar.xz
	"
fi
S="${WORKDIR}/${PN}-py-${PV}"

LICENSE="MIT"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD-2 MIT Unicode-3.0
	ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

src_configure() {
	export RUSTFLAGS="${RUSTFLAGS}"
	cargo_src_configure
}

src_compile() {
	cargo_src_compile

	python_copy_sources
	distutils-r1_src_compile
}

src_install() {
	distutils-r1_src_install
}

distutils_enable_tests pytest

src_test() {
	cargo_src_test

	rm -rf rjieba || die
	distutils-r1_src_test
}
