name: nvchecker

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 09:00 -> CST (China) 17:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 09 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nvchecker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/liangyongxiang/gentoo-testing:master
    outputs:
      nvcmp: ${{ steps.nvchecker.outputs.nvcmp }}
    steps:
    - name: checkout
      uses: actions/checkout@v5

    - name: gentoo
      run: |
        # eselect
        echo "::group::eselect repository add and sync"
        repo_name=$(cat profiles/repo_name)
        eselect repository add "$repo_name" git "file://${PWD}"
        emerge --sync "$repo_name"
        egencache --jobs=$(nproc) --update --repo "$repo_name" &> /dev/null
        eix-update
        echo "::endgroup::"
        # eix
        echo "::group::eix search packages"
        pkgs=$(ACCEPT_LICENSE="*" ACCEPT_KEYWORDS="~amd64 ~mips" EIX_LIMIT=0 NAMEVERSION="<category>/<name>-<version>\n" eix --pure-packages --in-overlay "$repo_name" --format '<bestversion:NAMEVERSION>')
        pkgs=$(qatom -F "\"%{CATEGORY}/%{PN}\": \"%{PV}\"," $pkgs) # remove revision
        echo "$pkgs"
        pkgs="{ ${pkgs::-1} }"
        echo "$pkgs" > .github/workflows/old_ver.json
        sed -r -i \
          -e 's#(\.|-|_)?p([[:digit:]]{8})(",?)$#\3#' \
          .github/workflows/old_ver.json
        cat .github/workflows/old_ver.json
        echo "::endgroup::"

        # homepage
        echo "::group::eix search homepage for packages"
        pkgs=$(ACCEPT_LICENSE="*" ACCEPT_KEYWORDS="~amd64 ~mips" EIX_LIMIT=0 NAMEVERSION='"<category>/<name>": "<homepage>", ' eix --pure-packages --in-overlay "$repo_name" --format '<bestversion:NAMEVERSION>')
        echo "$pkgs" | sed 's/, /\n/g'
        echo "{ ${pkgs::-2} }" | jq -c . > .github/workflows/homepages.json
        echo "::endgroup::"

    - name: nvchecker
      id: nvchecker
      env:
        GITHUB_TOKEN: ${{ secrets.NVCHECKER_PAT }}
      run: |
        echo "::group::nvchecker"
        cd .github/workflows/
        echo -e "[keys]\ngithub = \"${{ secrets.GITHUB_TOKEN }}\"" > keyfile.toml
        nvchecker --file overlay.toml --keyfile keyfile.toml
        echo "::endgroup::"

        echo "::group::nvcmp"
        sed -r -i \
          -e 's#(\.|-|_)?post([[:digit:]]+)(",?)$#_p\2\3#' \
          new_ver.json
        cat new_ver.json
        echo "nvcmp=$(nvcmp --file overlay.toml --json --newer | jq --slurpfile homepages homepages.json 'map({name, newver, oldver, homepage: ($homepages[0][.name] // null)})' | jq -c .)" >> $GITHUB_OUTPUT
        echo "::endgroup::"

  issues-bumper:
    needs: nvchecker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.nvchecker.outputs.nvcmp) }}
    steps:
    - name: Checkout bumpbot
      uses: actions/checkout@v5
      with:
        repository: 'wangjiezhe/gentoo-bumpbot'

    - name: Checkout gentoo-local
      uses: actions/checkout@v5
      with:
        path: 'gentoo-local'

    - name: update issues
      timeout-minutes: 1
      env:
        name: ${{ matrix.name }}
        newver: ${{ matrix.newver }}
        oldver: ${{ matrix.oldver }}
        homepage: ${{ matrix.homepage }}
        GITHUB_TOKEN: ${{ secrets.NVCHECKER_PAT }} # https://github.com/microcai/gentoo-zh/pull/3130
      run: |
        go run . --file gentoo-local/.github/workflows/overlay.toml --name "$name" --newver "$newver" --oldver "$oldver" --homepage "$homepage"
