[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

["sci-ml/caffe2"]
source = "github"
github = "pytorch/pytorch"
use_latest_release = true
prefix = "v"

["sci-ml/pytorch"]
source = "github"
github = "pytorch/pytorch"
use_latest_release = true
prefix = "v"

["sci-ml/torchvision"]
source = "github"
github = "pytorch/vision"
use_latest_release = true
prefix = "v"

["app-i18n/man-pages-zh_CN"]
source = "github"
github = "man-pages-zh/manpages-zh"
use_max_tag = true
prefix = "v"

["app-misc/cheat"]
source = "github"
github = "cheat/cheat"
use_latest_release = true

["app-emulation/wslu"]
source = "github"
github = "wslutilities/wslu"
use_latest_release = true
prefix = "v"

["app-vim/vimcdoc"]
source = "github"
github = "yianwillis/vimcdoc"
use_latest_release = true
prefix = "v"

["dev-haskell/plam"]
source = "github"
github = "sandrolovnicki/pLam"
use_latest_release = true
prefix = "v"

["sci-ml/FBGEMM"]
source = "github"
github = "pytorch/FBGEMM"
use_latest_release = true
prefix = "v"

["sci-ml/cudnn-frontend"]
source = "github"
github = "NVIDIA/cudnn-frontend"
use_latest_release = true
prefix = "v"

["dev-libs/cudnn"]
source = "regex"
url = "https://developer.download.nvidia.com/compute/cudnn/redist/cudnn/linux-x86_64/"
regex = "\\d+\\.\\d+\\.\\d+\\.\\d+"

["dev-libs/cutlass"]
source = "github"
github = "NVIDIA/cutlass"
use_max_tag = true
prefix = "v"

["sci-mathematics/mathematica"]
source = "aur"
aur = "mathematica"
strip_release = true

["sci-ml/lightning"]
source = "github"
github = "Lightning-AI/pytorch-lightning"
use_latest_release = true

["sci-ml/pytorch-lightning"]
source = "github"
github = "Lightning-AI/pytorch-lightning"
use_latest_release = true

["dev-libs/nccl"]
source = "github"
github = "NVIDIA/nccl"
use_max_tag = true
# prefix = "v"
from_pattern = 'v(\d+)\.(\d+)\.(\d+)-\d+'
to_pattern = '\1.\2.\3'

["dev-libs/cusparselt"]
source = "regex"
url = "https://developer.download.nvidia.com/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/"
regex = "\\d\\.\\d\\.\\d\\.\\d+"

["dev-python/pystoi"]
source = "github"
github = "mpariente/pystoi"
use_max_tag = true
prefix = "v"

["sci-ml/lightning-utilities"]
source = "github"
github = "Lightning-AI/utilities"
use_latest_release = true
prefix = "v"

["sci-ml/torchaudio"]
source = "github"
github = "pytorch/audio"
use_latest_release = true
prefix = "v"

["sci-ml/lpips"]
source = "github"
github = "richzhang/PerceptualSimilarity"
use_latest_release = true
prefix = "v"

["sci-ml/torch-fidelity"]
source = "github"
github = "toshas/torch-fidelity"
use_latest_release = true
prefix = "v"

["sci-ml/nltk"]
source = "github"
github = "nltk/nltk"
use_max_tag = true

["sci-ml/nltk-data"]
source = "github"
github = "nltk/nltk_data"
from_pattern = '(\d+)\.\d+'
to_pattern = '\1'

["sci-ml/torchmetrics"]
# source = "github"
# github = "Lightning-AI/torchmetrics"
# use_latest_release = true
# prefix = "v"
source = "pypi"
pypi = "torchmetrics"

["sci-ml/tensorrt"]
# source = "github"
# github = "NVIDIA/TensorRT"
# use_latest_release = true
# prefix = "v"
source = "aur"
aur = "tensorrt"
strip_release = true

["sci-ml/onnx"]
source = "github"
github = "onnx/onnx"
use_latest_release = true
prefix = "v"

["dev-python/h5py"]
source = "github"
github = "h5py/h5py"
use_latest_release = true

["dev-libs/dlpack"]
source = "github"
github = "dmlc/dlpack"
use_latest_release = true
prefix = "v"

# ["dev-cpp/catch"]
# source = "github"
# github = "catchorg/Catch2"
# use_latest_release = true
# prefix = "v"

# ["dev-python/statsmodels"]
# source = "github"
# github = "statsmodels/statsmodels"
# use_latest_release = true
# prefix = "v"

["net-libs/google-cloud-cpp"]
source = "github"
github = "googleapis/google-cloud-cpp"
use_latest_release = true
prefix = "v"

["sci-ml/torchinfo"]
source = "github"
github = "TylerYep/torchinfo"
use_latest_release = true
prefix = "v"

["sci-ml/kineto"]
source = "github"
github = "pytorch/kineto"
use_latest_release = true
prefix = "v"

["sci-ml/transformers"]
source = "github"
github = "huggingface/transformers"
use_latest_release = true
prefix = "v"

["sci-libs/magma"]
source = "github"
bitbucket = "icl-utk-edu/magma"
use_latest_release = true
prefix = "v"

["sci-ml/huggingface_hub"]
source = "github"
github = "huggingface/huggingface_hub"
use_latest_release = true
prefix = "v"

["dev-python/ml-dtypes"]
source = "github"
github = "jax-ml/ml_dtypes"
use_latest_release = true
prefix = "v"

["sci-ml/clean-fid"]
source = "pypi"
pypi = "clean-fid"

["sci-ml/framework-reproducibility"]
source = "github"
github = "NVIDIA/framework-reproducibility"
use_latest_release = true
prefix = "v"

["dev-python/expecttest"]
source = "pypi"
pypi = "expecttest"

["sci-ml/sentencepiece"]
source = "github"
github = "google/sentencepiece"
use_latest_release = true
prefix = "v"

["sci-ml/pysentencepiece"]
source = "github"
github = "google/sentencepiece"
use_latest_release = true
prefix = "v"

["dev-python/sacremoses"]
source = "github"
github = "hplt-project/sacremoses"
use_latest_release = true

["dev-python/revtok"]
source = "pypi"
pypi = "revtok"

["sci-ml/torchdata"]
source = "github"
github = "pytorch/data"
use_latest_release = true
prefix = "v"

["sci-ml/torchtext"]
source = "github"
github = "pytorch/text"
use_latest_release = true
prefix = "v"

["sci-ml/tensorflow"]
source = "github"
github = "tensorflow/tensorflow"
use_latest_release = true
prefix = "v"

["sci-visualization/tensorboard"]
source = "github"
github = "tensorflow/tensorboard"
use_latest_release = true
prefix = "v"

["sci-ml/keras"]
source = "github"
github = "keras-team/keras"
use_latest_release = true
prefix = "v"

["sci-ml/pytorch-image-models"]
source = "github"
github = "huggingface/pytorch-image-models"
use_latest_release = true
prefix = "v"

["dev-python/watermark"]
source = "pypi"
pypi = "watermark"

["dev-python/docker-pycreds"]
source = "github"
github = "shin-/dockerpy-creds"
use_max_tag = true

["sci-ml/wandb"]
source = "github"
github = "wandb/wandb"
use_latest_release = true
prefix = "v"

["dev-python/pyre-extensions"]
source = "pypi"
pypi = "pyre-extensions"

["sci-ml/torchtnt"]
source = "pypi"
pypi = "torchtnt"

["sci-ml/torcheval"]
source = "github"
github = "pytorch/torcheval"
use_latest_release = true

["dev-python/setuptools-git-version"]
source = "github"
github = "pyfidelity/setuptools-git-version"
use_latest_tag = true

["dev-python/setuptools-git-versioning"]
source = "github"
github = "dolfinus/setuptools-git-versioning"
use_latest_release = true
prefix = "v"

["dev-python/FBGEMM_GPU"]
source = "github"
github = "pytorch/FBGEMM"
use_latest_release = true
prefix = "v"

["dev-build/bazel"]
source = "github"
github = "bazelbuild/bazel"
use_latest_release = true

["dev-python/pyclibrary"]
source = "github"
github = "MatthieuDartiailh/pyclibrary"
use_latest_release = true

["dev-python/cuda-python"]
source = "github"
github = "NVIDIA/cuda-python"
use_latest_release = true
prefix = "v"

["dev-python/treelib"]
source = "github"
github = "caesar0301/treelib"
use_latest_release = true
prefix = "v"

["dev-python/cutlass"]
source = "github"
github = "NVIDIA/cutlass"
use_latest_release = true
prefix = "v"

["sci-ml/pytorch-msssim"]
source = "github"
github = "VainF/pytorch-msssim"
use_latest_release = true
prefix = "v"

["sci-ml/compressai"]
source = "github"
github = "InterDigitalInc/CompressAI"
use_latest_tag = true
prefix = "v"

["dev-python/sacrebleu"]
source = "github"
github = "mjpost/sacrebleu"
use_latest_tag = true
prefix = "v"

["dev-python/rouge-score"]
source = "pypi"
pypi = "rouge-score"

["dev-python/hf-doc-builder"]
source = "github"
github = "huggingface/doc-builder"
use_latest_tag = true
prefix = "v"

["dev-python/gql"]
source = "pypi"
pypi = "gql"

["sci-ml/faiss"]
source = "github"
github = "facebookresearch/faiss"
use_latest_release = true
prefix = "v"

["sci-ml/torchsnapshot"]
source = "github"
github = "pytorch/torchsnapshot"
use_latest_release = true

["dev-python/iopath"]
source = "pypi"
pypi = "iopath"

["sci-ml/torchrec"]
source = "github"
github = "pytorch/torchrec"
use_latest_release = true
prefix = "v"

["dev-python/rjieba"]
source = "github"
github = "messense/rjieba-py"
use_latest_tag = true
prefix = "v"

["sci-ml/accelerate"]
source = "github"
github = "huggingface/accelerate"
use_latest_release = true
prefix = "v"

["sci-ml/datasets"]
source = "github"
github = "huggingface/datasets"
use_latest_release = true

["sci-libs/aocl-blas"]
source = "github"
github = "amd/blis"
use_latest_release = true

["sci-libs/aocl-utils"]
source = "github"
github = "amd/aocl-utils"
use_latest_release = true

["sci-libs/aocl-lapack"]
source = "github"
github = "amd/libflame"
use_latest_release = true

["dev-python/astunparse"]
source = "github"
github = "simonpercivall/astunparse"
use_latest_tag = true
prefix = "v"

["dev-python/namex"]
source = "pypi"
pypi = "namex"

["dev-python/optree"]
source = "github"
github = "metaopt/optree"
use_latest_release = true
prefix = "v"

["dev-python/dm-tree"]
source = "github"
github = "google-deepmind/tree"
use_latest_release = true

["app-text/qtikz"]
source = "github"
github = "fhackenberger/ktikz"
use_latest_tag = true

["dev-util/evcxr-repl"]
source = "github"
github = "evcxr/evcxr"
use_latest_release = true
prefix = "v"

["net-vpn/frp"]
source = "github"
github = "fatedier/frp"
use_latest_release = true
prefix = "v"

["perl-gcpan/Neovim-Ext"]
source = "cpan"
cpan = "Neovim-Ext"

["perl-gcpan/MsgPack-Raw"]
source = "cpan"
cpan = "MsgPack-Raw"

["perl-gcpan/Eval-Safe"]
source = "cpan"
cpan = "Eval-Safe"

["net-misc/piping-server"]
source = "github"
github = "nwtgck/piping-server-rust"
use_latest_release = true
prefix = "v"

["sys-apps/bat-extras"]
source = "github"
github = "eth-p/bat-extras"
use_latest_release = true
prefix = "v"

["app-misc/cmd-wrapped"]
source = "github"
github = "YiNNx/cmd-wrapped"
use_latest_release = true
prefix = "v"

["app-text/typstyle"]
source = "github"
github = "Enter-tainer/typstyle"
use_latest_release = true
prefix = "v"

["dev-python/py3nvml"]
source = "pypi"
pypi = "py3nvml"

["sci-ml/tokenizers"]
source = "github"
github = "huggingface/tokenizers"
use_latest_release = true
prefix = "v"

["dev-util/minify-html"]
source = "github"
github = "wilsonzlin/minify-html"
use_latest_release = true
prefix = "v"

["dev-util/minify-js"]
source = "github"
github = "wilsonzlin/minify-js"
use_max_tag = true
prefix = "v"

["sci-libs/aocl-libm"]
source = "github"
github = "amd/aocl-libm-ose"
use_latest_release = true

["sci-libs/aocl-sparse"]
source = "github"
github = "amd/aocl-sparse"
use_latest_release = true

["dev-libs/cudss"]
source = "regex"
url = "https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-x86_64/"
regex = "\\d\\.\\d\\.\\d\\.\\d+"

["media-fonts/maple-mono"]
source = "github"
github = "subframe7536/maple-font"
use_latest_release = true
prefix = "v"

["app-laptop/thinkfan"]
source = "github"
github = "vmatare/thinkfan"
use_latest_release = true

["dev-python/clang-repl"]
source = "pypi"
pypi = "clang-repl"

["app-misc/aigit"]
source = "github"
github = "zzxwill/aigit"
use_latest_release = true
prefix = "v"

["dev-python/cuda-bindings"]
source = "github"
github = "NVIDIA/cuda-python"
use_max_release = true
prefix = "v"

["dev-python/cuda-core"]
source = "github"
github = "NVIDIA/cuda-python"
use_latest_release = true
prefix = "cuda-core-v"

["dev-util/gemini-cli"]
source = "github"
github = "google-gemini/gemini-cli"
use_max_release = true
prefix = "v"
exclude_regex = ".*nightly.*"

["media-gfx/pdf2svg"]
souce = "github"
github = "dawbarton/pdf2svg"
use_max_tag = true
prefix = "v"

["dev-util/mamba"]
source = "github"
github = "mamba-org/mamba"
use_latest_release = true

["dev-python/pyvers"]
souce = "github"
github = "vmoens/pyvers"
use_latest_release = true
prefix = "v"
