[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

["sci-libs/caffe2"]
source = "github"
github = "pytorch/pytorch"
use_latest_release = true
prefix = "v"

["sci-libs/pytorch"]
source = "github"
github = "pytorch/pytorch"
use_latest_release = true
prefix = "v"

["sci-libs/torchvision"]
source = "github"
github = "pytorch/vision"
use_latest_release = true
prefix = "v"

["app-i18n/man-pages-zh_CN"]
source = "github"
github = "man-pages-zh/manpages-zh"
use_max_tag = true
prefix = "v"

["app-misc/cheat"]
source = "github"
github = "cheat/cheat"
use_latest_release = true

["app-emulation/wslu"]
source = "github"
github = "wslutilities/wslu"
use_latest_release = true
prefix = "v"

["app-vim/vimcdoc"]
source = "github"
github = "yianwillis/vimcdoc"
use_latest_release = true
prefix = "v"

["dev-haskell/plam"]
source = "github"
github = "sandrolovnicki/pLam"
use_latest_release = true
prefix = "v"

["dev-libs/FBGEMM"]
source = "github"
github = "pytorch/FBGEMM"
use_latest_release = true
prefix = "v"

["dev-libs/cudnn-frontend"]
source = "github"
github = "NVIDIA/cudnn-frontend"
use_latest_release = true
prefix = "v"

["dev-libs/cudnn"]
source = "regex"
url = "https://developer.download.nvidia.cn/compute/cudnn/redist/cudnn/linux-x86_64/"
regex = "\\d\\.\\d\\.\\d\\.\\d+"

["dev-libs/cutlass"]
source = "github"
github = "NVIDIA/cutlass"
use_max_tag = true
prefix = "v"

["sci-mathematics/mathematica"]
source = "aur"
aur = "mathematica"
strip_release = true

["dev-python/lightning"]
source = "github"
github = "Lightning-AI/pytorch-lightning"
use_latest_release = true

["dev-python/pytorch-lightning"]
source = "github"
github = "Lightning-AI/pytorch-lightning"
use_latest_release = true

["dev-libs/nccl"]
source = "github"
github = "NVIDIA/nccl"
use_max_tag = true
# prefix = "v"
from_pattern = 'v(\d+)\.(\d+)\.(\d+)-\d+'
to_pattern = '\1.\2.\3'

["dev-libs/cusparselt"]
source = "regex"
url = "https://developer.download.nvidia.cn/compute/cusparselt/redist/libcusparse_lt/linux-x86_64/"
regex = "\\d\\.\\d\\.\\d\\.\\d+"

["dev-python/pystoi"]
source = "github"
github = "mpariente/pystoi"
use_max_tag = true
prefix = "v"

["dev-python/lightning-utilities"]
source = "github"
github = "Lightning-AI/utilities"
use_latest_release = true
prefix = "v"

["sci-libs/torchaudio"]
source = "github"
github = "pytorch/audio"
use_latest_release = true
prefix = "v"

["sci-libs/lpips"]
source = "github"
github = "richzhang/PerceptualSimilarity"
use_latest_release = true
prefix = "v"

["sci-libs/torch-fidelity"]
source = "github"
github = "toshas/torch-fidelity"
use_latest_release = true
prefix = "v"

["sci-libs/nltk"]
source = "github"
github = "nltk/nltk"
use_max_tag = true

["sci-libs/nltk-data"]
source = "github"
github = "nltk/nltk_data"
from_pattern = '(\d+)\.\d+'
to_pattern = '\1'

["sci-libs/torchmetrics"]
# source = "github"
# github = "Lightning-AI/torchmetrics"
# use_latest_release = true
# prefix = "v"
source = "pypi"
pypi = "torchmetrics"

["sci-libs/tensorrt"]
# source = "github"
# github = "NVIDIA/TensorRT"
# use_latest_release = true
# prefix = "v"
source = "aur"
aur = "tensorrt"
strip_release = true

["sci-libs/onnx"]
source = "github"
github = "onnx/onnx"
use_latest_release = true
prefix = "v"

["dev-python/h5py"]
source = "github"
github = "h5py/h5py"
use_latest_release = true

["dev-libs/dlpack"]
source = "github"
github = "dmlc/dlpack"
use_latest_release = true
prefix = "v"

["dev-libs/catch2"]
source = "github"
github = "catchorg/Catch2"
use_latest_release = true
prefix = "v"

["dev-python/statsmodels"]
source = "github"
github = "statsmodels/statsmodels"
use_latest_release = true
prefix = "v"

["net-libs/google-cloud-cpp"]
source = "github"
github = "googleapis/google-cloud-cpp"
use_latest_release = true
prefix = "v"

["dev-python/torchinfo"]
source = "github"
github = "TylerYep/torchinfo"
use_latest_release = true
prefix = "v"

["sci-libs/kineto"]
source = "github"
github = "pytorch/kineto"
use_latest_release = true
prefix = "v"

["sci-libs/transformers"]
source = "github"
github = "huggingface/transformers"
use_latest_release = true
prefix = "v"

["sci-libs/magma"]
source = "bitbucket"
bitbucket = "icl/magma"
use_max_tag = true
prefix = "v"

["sci-libs/huggingface_hub"]
source = "github"
github = "huggingface/huggingface_hub"
use_latest_release = true
prefix = "v"

["dev-python/ml-dtypes"]
source = "github"
github = "jax-ml/ml_dtypes"
use_latest_release = true
prefix = "v"

["sci-libs/clean-fid"]
source = "pypi"
pypi = "clean-fid"

["sci-libs/framework-reproducibility"]
source = "github"
github = "NVIDIA/framework-reproducibility"
use_latest_release = true
prefix = "v"

["dev-python/expecttest"]
source = "pypi"
pypi = "expecttest"

["dev-libs/sentencepiece"]
source = "github"
github = "google/sentencepiece"
use_latest_release = true
prefix = "v"

["dev-python/sentencepiece"]
source = "github"
github = "google/sentencepiece"
use_latest_release = true
prefix = "v"

["dev-python/sacremoses"]
source = "github"
github = "hplt-project/sacremoses"
use_latest_release = true

["dev-python/revtok"]
source = "pypi"
pypi = "revtok"

["sci-libs/torchdata"]
source = "github"
github = "pytorch/data"
use_latest_release = true
prefix = "v"

["sci-libs/torchtext"]
source = "github"
github = "pytorch/text"
use_latest_release = true
prefix = "v"

["net-libs/grpc"]
source = "github"
github = "grpc/grpc"
use_latest_release = true
prefix = "v"

["dev-python/grpcio"]
source = "pypi"
pypi = "grpcio"

["dev-cpp/abseil-cpp"]
source = "github"
github = "abseil/abseil-cpp"
use_latest_release = true

["sci-libs/tensorflow"]
source = "github"
github = "tensorflow/tensorflow"
use_latest_release = true
prefix = "v"

["sci-visualization/tensorboard"]
source = "github"
github = "tensorflow/tensorboard"
use_latest_release = true
prefix = "v"

["sci-libs/tensorflow-estimator"]
source = "github"
github = "tensorflow/estimator"
use_latest_release = true
prefix = "v"

["sci-libs/keras"]
source = "github"
github = "keras-team/keras"
use_latest_release = true
prefix = "v"

["sci-libs/pytorch-image-models"]
source = "github"
github = "huggingface/pytorch-image-models"
use_latest_release = true
prefix = "v"

["dev-python/watermark"]
source = "pypi"
pypi = "watermark"

["dev-python/docker-pycreds"]
source = "github"
github = "shin-/dockerpy-creds"
use_max_tag = true

["dev-python/wandb"]
source = "github"
github = "wandb/wandb"
use_latest_release = true
prefix = "v"

["dev-python/pyre-extensions"]
source = "pypi"
pypi = "pyre-extensions"

["sci-libs/torchtnt"]
source = "pypi"
pypi = "torchtnt"

["sci-libs/torcheval"]
source = "github"
github = "pytorch/torcheval"
use_latest_release = true

["dev-python/setuptools-git-version"]
source = "github"
github = "pyfidelity/setuptools-git-version"
use_latest_tag = true

["dev-python/setuptools-git-versioning"]
source = "github"
github = "dolfinus/setuptools-git-versioning"
use_latest_release = true
prefix = "v"

["dev-python/FBGEMM_GPU"]
source = "github"
github = "pytorch/FBGEMM"
use_latest_release = true
prefix = "v"

["dev-build/bazel"]
source = "github"
github = "bazelbuild/bazel"
use_latest_release = true

["dev-python/pyclibrary"]
source = "github"
github = "MatthieuDartiailh/pyclibrary"
use_latest_release = true

["dev-python/cuda-python"]
source = "github"
github = "NVIDIA/cuda-python"
use_latest_release = true
prefix = "v"

["dev-python/treelib"]
source = "github"
github = "caesar0301/treelib"
use_latest_release = true
prefix = "v"

["dev-python/cutlass"]
source = "github"
github = "NVIDIA/cutlass"
use_latest_release = true
prefix = "v"

["sci-libs/pytorch-msssim"]
source = "github"
github = "VainF/pytorch-msssim"
use_latest_release = true
prefix = "v"

["sci-libs/compressai"]
source = "github"
github = "InterDigitalInc/CompressAI"
use_latest_tag = true
prefix = "v"

["dev-python/sacrebleu"]
source = "github"
github = "mjpost/sacrebleu"
use_latest_tag = true
prefix = "v"

["dev-python/rouge-score"]
source = "pypi"
pypi = "rouge-score"

["dev-python/hf-doc-builder"]
source = "github"
github = "huggingface/doc-builder"
use_latest_tag = true
prefix = "v"

["dev-python/gql"]
source = "pypi"
pypi = "gql"

["sci-libs/faiss"]
source = "github"
github = "facebookresearch/faiss"
use_latest_release = true
prefix = "v"

["sci-libs/torchsnapshot"]
source = "github"
github = "pytorch/torchsnapshot"
use_latest_release = true

["dev-python/iopath"]
source = "pypi"
pypi = "iopath"

["sci-libs/torchrec"]
source = "github"
github = "pytorch/torchrec"
use_latest_release = true
prefix = "v"

["dev-python/rjieba"]
source = "github"
github = "messense/rjieba-py"
use_latest_tag = true
prefix = "v"

["sci-libs/accelerate"]
source = "github"
github = "huggingface/accelerate"
use_latest_release = true
prefix = "v"

["sci-libs/datasets"]
source = "github"
github = "huggingface/datasets"
use_latest_release = true

["sci-libs/aocl-blas"]
source = "github"
github = "amd/blis"
use_latest_release = true

["sci-libs/aocl-utils"]
source = "github"
github = "amd/aocl-utils"
use_latest_release = true

["sci-libs/aocl-lapack"]
source = "github"
github = "amd/libflame"
use_latest_release = true

["dev-python/astunparse"]
source = "github"
github = "simonpercivall/astunparse"
use_latest_tag = true

["dev-python/namex"]
source = "pypi"
pypi = "namex"

["dev-python/optree"]
source = "github"
github = "metaopt/optree"
use_latest_release = true
prefix = "v"
